DROP TABLE IF EXISTS new_refs_equis;
DROP TABLE IF EXISTS new_strain_designations;

SELECT *
INTO new_refs_equis
FROM all_strains_grouped
WHERE short_strain LIKE ANY(SELECT CONCAT(collection, '%') FROM bilan_collections)
OR short_strain SIMILAR TO '(CARE|CRBIP|CIP|DSM|ATCC|JCM|NCTC|WDCM|LMG|ICMP|CBS|NRIC|RIA|IFM|TISTR|BCRC|PCM|CSUR|PCU|BCC|CCTM|NBIMCC|CNCTC|MCCC|HAMBI|NCCB|HUT|NCB|UCM|MCCM|CCBAU|TMC|CCT|MCC|MOLA|VKPM|ACCC|ATCC|CIP|MBIC|AHU|BTCC|CBMAI|CFCC|IID|KOS|MDC|NCDC|RIMD|VTCC|ZIM|ATU|BGSC|BR|BRCC|CB|CIAT|CNCM|IEBC|IFAM|NCCP|OCM|OUT|RIFY|RSKK|NCDO|KCCM|CCRC|KCC)%';

SELECT * 
INTO new_strain_designations
FROM all_strains_grouped
WHERE (xxx_id, short_strain, position) NOT IN (SELECT * FROM new_refs_equis);
