DROP TABLE IF EXISTS strains_bacillus;
DROP TABLE IF EXISTS new_strains_bacillus;
DROP TABLE IF EXISTS all_strains;
DROP TABLE IF EXISTS bad_strains;
DROP TABLE IF EXISTS temp_taxo;
DROP TABLE IF EXISTS casser_les_egaux;
DROP TABLE IF EXISTS casser_les_strains;
DROP TABLE IF EXISTS new_refs_equis;
DROP TABLE IF EXISTS doublons;
